sudo: false

language: python

jobs:
  include:

    - stage: linux
      os: linux
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env: 
        - BADGE=linux
      install:
        - pip install -r requirements-tox.txt
        - pip install -e . # Install local package with dependencies
      script:
        - tox
